const data = {
    products:[
        {
            _id:'1',
            name:'DW CLASSIC ST MAWES',
            category: 'Women',
            image:'/images/product1.jpg',
            price:150,
            countInStock: 10,
            brand:'Daniel Wellington',
            rating:5,
            numReviews:10,
            description:'High quality product.',
        },
        {
            _id:'2',
            name:'DW PETITE MELROSE',
            category: 'Women',
            image:'/images/product2.jpeg',
            price:120,
            countInStock: 20,
            brand:'Daniel Wellington',
            rating:3,
            numReviews:20,
            description:'High quality product.',
        },
        {
            _id:'3',
            name:'DW PETITE UNITONE',
            category: 'Women',
            image:'/images/product3.jpg',
            price:110,
            countInStock: 10,
            brand:'Daniel Wellington',
            rating:4.5,
            numReviews:11,
            description:'High quality product.',
        },
        {
            _id:'4',
            name:'DW ICONIC LINK ARCTIC',
            category: 'Men',
            image:'/images/product4.jpg',
            price:190,
            countInStock: 30,
            brand:'Daniel Wellington',
            rating:1,
            numReviews:16,
            description:'High quality product.',
        },
        {
            _id:'5',
            name:'DW ICONIC LINK UNITONE',
            category: 'Men',
            image:'/images/product5.jpg',
            price:155,
            countInStock: 20,
            brand:'Daniel Wellington',
            rating:4,
            numReviews:14,
            description:'High quality product.'
        },
        {
            _id:'6',
            name:'DW ICONIC LINK AMBER',
            category: 'Men',
            image:'/images/product6.jpg',
            price:100,
            countInStock: 10,
            brand:'Daniel Wellington',
            rating:3,
            numReviews:13,
            description:'High quality product.',
        },
        {
            _id:'7',
            name:'DW PRESSED MELROSE',
            category: 'Women',
            image:'/images/product7.jpg',
            price:130,
            countInStock: 10,
            brand:'Daniel Wellington',
            rating:5,
            numReviews:16,
            description:'High quality product.',
        },
    ],
};

export default data;