const data = {
    products:[
        {
            _id:'1',
            name:'DW CLASSIC ST MAWES',
            category: 'Women',
            image:'/images/product1.jpg',
            price:150,
            countInStock: 10,
            brand:'Daniel Wellington',
            rating:5,
            numReviews: 10,
            description:'High quality product.',
        },
        {
            _id:'2',
            name:'DW Classic St Mawes',
            category: 'Women',
            image:'/images/product1.jpg',
            price:150,
            countInStock: 20,
            brand:'Daniel Wellington',
            rating:5,
            numReviews:10,
            description:'High quality product.',
        },
        {
            _id:'3',
            name:'DW Classic St Mawes',
            category: 'Women',
            image:'/images/product1.jpg',
            price:150,
            countInStock: 10,
            brand:'Daniel Wellington',
            rating:5,
            numReviews:10,
            description:'High quality product.',
        },
        {
            _id:'4',
            name:'DW Classic St Mawes',
            category: 'Women',
            image:'/images/product1.jpg',
            price:150,
            countInStock: 30,
            brand:'Daniel Wellington',
            rating:5,
            numReviews:10,
            description:'High quality product.',
        },
        {
            _id:'5',
            name:'DW Classic St Mawes',
            category: 'Women',
            image:'/images/product1.jpg',
            price:150,
            countInStock: 20,
            brand:'Daniel Wellington',
            rating:5,
            numReviews:10,
            description:'High quality product.'
        },
        {
            _id:'6',
            name:'DW Classic St Mawes',
            category: 'Women',
            image:'/images/product1.jpg',
            price:150,
            countInStock: 10,
            brand:'Daniel Wellington',
            rating:5,
            numReviews:10,
            description:'High quality product.',
        },
        {
            _id:'7',
            name:'DW Classic St Mawes',
            category: 'Women',
            image:'/images/product1.jpg',
            price:150,
            countInStock: 10,
            brand:'Daniel Wellington',
            rating:5,
            numReviews:10,
            description:'High quality product.',
        },
    ],
};

export default data;